# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BinaryOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BinaryOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBinaryOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BinaryOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BinaryOp
    def OpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BinaryOp
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # BinaryOp
    def ActivationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def BinaryOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    BinaryOpStart(builder)

def BinaryOpAddOpType(builder, opType):
    builder.PrependInt32Slot(0, opType, 0)

def AddOpType(builder, opType):
    BinaryOpAddOpType(builder, opType)

def BinaryOpAddT(builder, t):
    builder.PrependInt32Slot(1, t, 1)

def AddT(builder, t):
    BinaryOpAddT(builder, t)

def BinaryOpAddActivationType(builder, activationType):
    builder.PrependInt32Slot(2, activationType, 0)

def AddActivationType(builder, activationType):
    BinaryOpAddActivationType(builder, activationType)

def BinaryOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return BinaryOpEnd(builder)
