# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CastParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CastParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCastParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CastParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CastParam
    def SrcT(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CastParam
    def DstT(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def CastParamStart(builder):
    builder.StartObject(2)

def Start(builder):
    CastParamStart(builder)

def CastParamAddSrcT(builder, srcT):
    builder.PrependInt32Slot(0, srcT, 0)

def AddSrcT(builder, srcT):
    CastParamAddSrcT(builder, srcT)

def CastParamAddDstT(builder, dstT):
    builder.PrependInt32Slot(1, dstT, 0)

def AddDstT(builder, dstT):
    CastParamAddDstT(builder, dstT)

def CastParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return CastParamEnd(builder)
