# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DepthSpaceParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DepthSpaceParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDepthSpaceParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DepthSpaceParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DepthSpaceParam
    def BlockSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DepthSpaceParam
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def DepthSpaceParamStart(builder):
    builder.StartObject(2)

def Start(builder):
    DepthSpaceParamStart(builder)

def DepthSpaceParamAddBlockSize(builder, blockSize):
    builder.PrependInt32Slot(0, blockSize, 0)

def AddBlockSize(builder, blockSize):
    DepthSpaceParamAddBlockSize(builder, blockSize)

def DepthSpaceParamAddMode(builder, mode):
    builder.PrependInt8Slot(1, mode, 0)

def AddMode(builder, mode):
    DepthSpaceParamAddMode(builder, mode)

def DepthSpaceParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return DepthSpaceParamEnd(builder)
