# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Eltwise(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Eltwise()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEltwise(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Eltwise
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Eltwise
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Eltwise
    def Coeff(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Eltwise
    def CoeffAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Eltwise
    def CoeffLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Eltwise
    def CoeffIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def EltwiseStart(builder):
    builder.StartObject(2)

def Start(builder):
    EltwiseStart(builder)

def EltwiseAddType(builder, type):
    builder.PrependInt8Slot(0, type, 0)

def AddType(builder, type):
    EltwiseAddType(builder, type)

def EltwiseAddCoeff(builder, coeff):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(coeff), 0)

def AddCoeff(builder, coeff):
    EltwiseAddCoeff(builder, coeff)

def EltwiseStartCoeffVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCoeffVector(builder, numElems: int) -> int:
    return EltwiseStartCoeffVector(builder, numElems)

def EltwiseEnd(builder):
    return builder.EndObject()

def End(builder):
    return EltwiseEnd(builder)
