# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExpandDims(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExpandDims()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExpandDims(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ExpandDims
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExpandDims
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ExpandDims
    def Tdim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ExpandDims
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ExpandDimsStart(builder):
    builder.StartObject(3)

def Start(builder):
    ExpandDimsStart(builder)

def ExpandDimsAddT(builder, t):
    builder.PrependInt32Slot(0, t, 0)

def AddT(builder, t):
    ExpandDimsAddT(builder, t)

def ExpandDimsAddTdim(builder, tdim):
    builder.PrependInt32Slot(1, tdim, 0)

def AddTdim(builder, tdim):
    ExpandDimsAddTdim(builder, tdim)

def ExpandDimsAddAxis(builder, axis):
    builder.PrependInt32Slot(2, axis, 0)

def AddAxis(builder, axis):
    ExpandDimsAddAxis(builder, axis)

def ExpandDimsEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExpandDimsEnd(builder)
