# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GroupNorm(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GroupNorm()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGroupNorm(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GroupNorm
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GroupNorm
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroupNorm
    def Epsilon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GroupNorm
    def Gamma(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GroupNorm
    def GammaAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # GroupNorm
    def GammaLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroupNorm
    def GammaIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # GroupNorm
    def Beta(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GroupNorm
    def BetaAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # GroupNorm
    def BetaLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroupNorm
    def BetaIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # GroupNorm
    def Group(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # GroupNorm
    def BSwish(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroupNorm
    def External(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # GroupNorm
    def ExternalAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # GroupNorm
    def ExternalLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroupNorm
    def ExternalIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def GroupNormStart(builder):
    builder.StartObject(7)

def Start(builder):
    GroupNormStart(builder)

def GroupNormAddAxis(builder, axis):
    builder.PrependInt32Slot(0, axis, 0)

def AddAxis(builder, axis):
    GroupNormAddAxis(builder, axis)

def GroupNormAddEpsilon(builder, epsilon):
    builder.PrependFloat32Slot(1, epsilon, 0.0)

def AddEpsilon(builder, epsilon):
    GroupNormAddEpsilon(builder, epsilon)

def GroupNormAddGamma(builder, gamma):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(gamma), 0)

def AddGamma(builder, gamma):
    GroupNormAddGamma(builder, gamma)

def GroupNormStartGammaVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGammaVector(builder, numElems: int) -> int:
    return GroupNormStartGammaVector(builder, numElems)

def GroupNormAddBeta(builder, beta):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(beta), 0)

def AddBeta(builder, beta):
    GroupNormAddBeta(builder, beta)

def GroupNormStartBetaVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBetaVector(builder, numElems: int) -> int:
    return GroupNormStartBetaVector(builder, numElems)

def GroupNormAddGroup(builder, group):
    builder.PrependInt32Slot(4, group, 1)

def AddGroup(builder, group):
    GroupNormAddGroup(builder, group)

def GroupNormAddBSwish(builder, bSwish):
    builder.PrependInt32Slot(5, bSwish, 0)

def AddBSwish(builder, bSwish):
    GroupNormAddBSwish(builder, bSwish)

def GroupNormAddExternal(builder, external):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(external), 0)

def AddExternal(builder, external):
    GroupNormAddExternal(builder, external)

def GroupNormStartExternalVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartExternalVector(builder, numElems: int) -> int:
    return GroupNormStartExternalVector(builder, numElems)

def GroupNormEnd(builder):
    return builder.EndObject()

def End(builder):
    return GroupNormEnd(builder)
