# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IDSTQuan(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IDSTQuan()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIDSTQuan(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IDSTQuan
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IDSTQuan
    def Buffer(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # IDSTQuan
    def BufferAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # IDSTQuan
    def BufferLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IDSTQuan
    def BufferIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # IDSTQuan
    def Alpha(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IDSTQuan
    def AlphaAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # IDSTQuan
    def AlphaLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IDSTQuan
    def AlphaIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # IDSTQuan
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IDSTQuan
    def UseInt32(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # IDSTQuan
    def QuantScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # IDSTQuan
    def ScaleIn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # IDSTQuan
    def ScaleOut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # IDSTQuan
    def AMaxOrBits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IDSTQuan
    def AMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IDSTQuan
    def ReadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IDSTQuan
    def HasScaleInt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # IDSTQuan
    def ShapeInt32(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # IDSTQuan
    def WeightSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # IDSTQuan
    def Index(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IDSTQuan
    def IndexAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # IDSTQuan
    def IndexLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IDSTQuan
    def IndexIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

def IDSTQuanStart(builder):
    builder.StartObject(14)

def Start(builder):
    IDSTQuanStart(builder)

def IDSTQuanAddBuffer(builder, buffer):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(buffer), 0)

def AddBuffer(builder, buffer):
    IDSTQuanAddBuffer(builder, buffer)

def IDSTQuanStartBufferVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartBufferVector(builder, numElems: int) -> int:
    return IDSTQuanStartBufferVector(builder, numElems)

def IDSTQuanAddAlpha(builder, alpha):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(alpha), 0)

def AddAlpha(builder, alpha):
    IDSTQuanAddAlpha(builder, alpha)

def IDSTQuanStartAlphaVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAlphaVector(builder, numElems: int) -> int:
    return IDSTQuanStartAlphaVector(builder, numElems)

def IDSTQuanAddType(builder, type):
    builder.PrependInt32Slot(2, type, 0)

def AddType(builder, type):
    IDSTQuanAddType(builder, type)

def IDSTQuanAddUseInt32(builder, useInt32):
    builder.PrependBoolSlot(3, useInt32, 0)

def AddUseInt32(builder, useInt32):
    IDSTQuanAddUseInt32(builder, useInt32)

def IDSTQuanAddQuantScale(builder, quantScale):
    builder.PrependFloat32Slot(4, quantScale, 0.0)

def AddQuantScale(builder, quantScale):
    IDSTQuanAddQuantScale(builder, quantScale)

def IDSTQuanAddScaleIn(builder, scaleIn):
    builder.PrependFloat32Slot(5, scaleIn, 0.0)

def AddScaleIn(builder, scaleIn):
    IDSTQuanAddScaleIn(builder, scaleIn)

def IDSTQuanAddScaleOut(builder, scaleOut):
    builder.PrependFloat32Slot(6, scaleOut, 0.0)

def AddScaleOut(builder, scaleOut):
    IDSTQuanAddScaleOut(builder, scaleOut)

def IDSTQuanAddAMaxOrBits(builder, aMaxOrBits):
    builder.PrependInt32Slot(7, aMaxOrBits, 0)

def AddAMaxOrBits(builder, aMaxOrBits):
    IDSTQuanAddAMaxOrBits(builder, aMaxOrBits)

def IDSTQuanAddAMin(builder, aMin):
    builder.PrependInt32Slot(8, aMin, 0)

def AddAMin(builder, aMin):
    IDSTQuanAddAMin(builder, aMin)

def IDSTQuanAddReadType(builder, readType):
    builder.PrependInt32Slot(9, readType, 0)

def AddReadType(builder, readType):
    IDSTQuanAddReadType(builder, readType)

def IDSTQuanAddHasScaleInt(builder, hasScaleInt):
    builder.PrependBoolSlot(10, hasScaleInt, 0)

def AddHasScaleInt(builder, hasScaleInt):
    IDSTQuanAddHasScaleInt(builder, hasScaleInt)

def IDSTQuanAddShapeInt32(builder, shapeInt32):
    builder.PrependBoolSlot(11, shapeInt32, 0)

def AddShapeInt32(builder, shapeInt32):
    IDSTQuanAddShapeInt32(builder, shapeInt32)

def IDSTQuanAddWeightSize(builder, weightSize):
    builder.PrependUint32Slot(12, weightSize, 0)

def AddWeightSize(builder, weightSize):
    IDSTQuanAddWeightSize(builder, weightSize)

def IDSTQuanAddIndex(builder, index):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(index), 0)

def AddIndex(builder, index):
    IDSTQuanAddIndex(builder, index)

def IDSTQuanStartIndexVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartIndexVector(builder, numElems: int) -> int:
    return IDSTQuanStartIndexVector(builder, numElems)

def IDSTQuanEnd(builder):
    return builder.EndObject()

def End(builder):
    return IDSTQuanEnd(builder)
