# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Input(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Input()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Input
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Input
    def Dims(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Input
    def DimsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Input
    def DimsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Input
    def DimsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Input
    def Dtype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # Input
    def Dformat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 2

def InputStart(builder):
    builder.StartObject(3)

def Start(builder):
    InputStart(builder)

def InputAddDims(builder, dims):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dims), 0)

def AddDims(builder, dims):
    InputAddDims(builder, dims)

def InputStartDimsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDimsVector(builder, numElems: int) -> int:
    return InputStartDimsVector(builder, numElems)

def InputAddDtype(builder, dtype):
    builder.PrependInt32Slot(1, dtype, 1)

def AddDtype(builder, dtype):
    InputAddDtype(builder, dtype)

def InputAddDformat(builder, dformat):
    builder.PrependInt8Slot(2, dformat, 2)

def AddDformat(builder, dformat):
    InputAddDformat(builder, dformat)

def InputEnd(builder):
    return builder.EndObject()

def End(builder):
    return InputEnd(builder)
