# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LayerNorm(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LayerNorm()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLayerNorm(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LayerNorm
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LayerNorm
    def Axis(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # LayerNorm
    def AxisAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # LayerNorm
    def AxisLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LayerNorm
    def AxisIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # LayerNorm
    def Epsilon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # LayerNorm
    def Gamma(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # LayerNorm
    def GammaAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # LayerNorm
    def GammaLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LayerNorm
    def GammaIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # LayerNorm
    def Beta(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # LayerNorm
    def BetaAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # LayerNorm
    def BetaLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LayerNorm
    def BetaIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # LayerNorm
    def Group(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # LayerNorm
    def External(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # LayerNorm
    def ExternalAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # LayerNorm
    def ExternalLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LayerNorm
    def ExternalIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # LayerNorm
    def UseRmsnorm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def LayerNormStart(builder):
    builder.StartObject(7)

def Start(builder):
    LayerNormStart(builder)

def LayerNormAddAxis(builder, axis):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(axis), 0)

def AddAxis(builder, axis):
    LayerNormAddAxis(builder, axis)

def LayerNormStartAxisVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAxisVector(builder, numElems: int) -> int:
    return LayerNormStartAxisVector(builder, numElems)

def LayerNormAddEpsilon(builder, epsilon):
    builder.PrependFloat32Slot(1, epsilon, 0.0)

def AddEpsilon(builder, epsilon):
    LayerNormAddEpsilon(builder, epsilon)

def LayerNormAddGamma(builder, gamma):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(gamma), 0)

def AddGamma(builder, gamma):
    LayerNormAddGamma(builder, gamma)

def LayerNormStartGammaVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGammaVector(builder, numElems: int) -> int:
    return LayerNormStartGammaVector(builder, numElems)

def LayerNormAddBeta(builder, beta):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(beta), 0)

def AddBeta(builder, beta):
    LayerNormAddBeta(builder, beta)

def LayerNormStartBetaVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBetaVector(builder, numElems: int) -> int:
    return LayerNormStartBetaVector(builder, numElems)

def LayerNormAddGroup(builder, group):
    builder.PrependInt32Slot(4, group, 1)

def AddGroup(builder, group):
    LayerNormAddGroup(builder, group)

def LayerNormAddExternal(builder, external):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(external), 0)

def AddExternal(builder, external):
    LayerNormAddExternal(builder, external)

def LayerNormStartExternalVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartExternalVector(builder, numElems: int) -> int:
    return LayerNormStartExternalVector(builder, numElems)

def LayerNormAddUseRmsnorm(builder, useRmsnorm):
    builder.PrependBoolSlot(6, useRmsnorm, 0)

def AddUseRmsnorm(builder, useRmsnorm):
    LayerNormAddUseRmsnorm(builder, useRmsnorm)

def LayerNormEnd(builder):
    return builder.EndObject()

def End(builder):
    return LayerNormEnd(builder)
