# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NamedAttrList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NamedAttrList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNamedAttrList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NamedAttrList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NamedAttrList
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NamedAttrList
    def Attr(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MNN.Attribute import Attribute
            obj = Attribute()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NamedAttrList
    def AttrLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NamedAttrList
    def AttrIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def NamedAttrListStart(builder):
    builder.StartObject(2)

def Start(builder):
    NamedAttrListStart(builder)

def NamedAttrListAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    NamedAttrListAddName(builder, name)

def NamedAttrListAddAttr(builder, attr):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(attr), 0)

def AddAttr(builder, attr):
    NamedAttrListAddAttr(builder, attr)

def NamedAttrListStartAttrVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAttrVector(builder, numElems: int) -> int:
    return NamedAttrListStartAttrVector(builder, numElems)

def NamedAttrListEnd(builder):
    return builder.EndObject()

def End(builder):
    return NamedAttrListEnd(builder)
