# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OneHotParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OneHotParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOneHotParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OneHotParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OneHotParam
    def DType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # OneHotParam
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

def OneHotParamStart(builder):
    builder.StartObject(2)

def Start(builder):
    OneHotParamStart(builder)

def OneHotParamAddDType(builder, dType):
    builder.PrependInt32Slot(0, dType, 1)

def AddDType(builder, dType):
    OneHotParamAddDType(builder, dType)

def OneHotParamAddAxis(builder, axis):
    builder.PrependInt32Slot(1, axis, -1)

def AddAxis(builder, axis):
    OneHotParamAddAxis(builder, axis)

def OneHotParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return OneHotParamEnd(builder)
