# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuantizeMaxMin(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuantizeMaxMin()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuantizeMaxMin(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuantizeMaxMin
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizeMaxMin
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def QuantizeMaxMinStart(builder):
    builder.StartObject(1)

def Start(builder):
    QuantizeMaxMinStart(builder)

def QuantizeMaxMinAddT(builder, t):
    builder.PrependInt32Slot(0, t, 0)

def AddT(builder, t):
    QuantizeMaxMinAddT(builder, t)

def QuantizeMaxMinEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuantizeMaxMinEnd(builder)
