# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuantizeV2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuantizeV2()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuantizeV2(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuantizeV2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizeV2
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # QuantizeV2
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # QuantizeV2
    def RoundMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def QuantizeV2Start(builder):
    builder.StartObject(3)

def Start(builder):
    QuantizeV2Start(builder)

def QuantizeV2AddType(builder, type):
    builder.PrependInt32Slot(0, type, 0)

def AddType(builder, type):
    QuantizeV2AddType(builder, type)

def QuantizeV2AddMode(builder, mode):
    builder.PrependInt8Slot(1, mode, 0)

def AddMode(builder, mode):
    QuantizeV2AddMode(builder, mode)

def QuantizeV2AddRoundMode(builder, roundMode):
    builder.PrependInt8Slot(2, roundMode, 0)

def AddRoundMode(builder, roundMode):
    QuantizeV2AddRoundMode(builder, roundMode)

def QuantizeV2End(builder):
    return builder.EndObject()

def End(builder):
    return QuantizeV2End(builder)
