# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Rank(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Rank()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRank(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Rank
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def RankStart(builder):
    builder.StartObject(0)

def Start(builder):
    RankStart(builder)

def RankEnd(builder):
    return builder.EndObject()

def End(builder):
    return RankEnd(builder)
