# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReduceJoin(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReduceJoin()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReduceJoin(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReduceJoin
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReduceJoin
    def KeepDims(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ReduceJoin
    def Separator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ReduceJoinStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReduceJoinStart(builder)

def ReduceJoinAddKeepDims(builder, keepDims):
    builder.PrependBoolSlot(0, keepDims, 0)

def AddKeepDims(builder, keepDims):
    ReduceJoinAddKeepDims(builder, keepDims)

def ReduceJoinAddSeparator(builder, separator):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(separator), 0)

def AddSeparator(builder, separator):
    ReduceJoinAddSeparator(builder, separator)

def ReduceJoinEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReduceJoinEnd(builder)
