# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Relu6(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Relu6()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRelu6(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Relu6
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Relu6
    def MinValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Relu6
    def MaxValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 6.0

def Relu6Start(builder):
    builder.StartObject(2)

def Start(builder):
    Relu6Start(builder)

def Relu6AddMinValue(builder, minValue):
    builder.PrependFloat32Slot(0, minValue, 0.0)

def AddMinValue(builder, minValue):
    Relu6AddMinValue(builder, minValue)

def Relu6AddMaxValue(builder, maxValue):
    builder.PrependFloat32Slot(1, maxValue, 6.0)

def AddMaxValue(builder, maxValue):
    Relu6AddMaxValue(builder, maxValue)

def Relu6End(builder):
    return builder.EndObject()

def End(builder):
    return Relu6End(builder)
