# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StftParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StftParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStftParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StftParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StftParam
    def NFft(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StftParam
    def HopLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StftParam
    def Abs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def StftParamStart(builder):
    builder.StartObject(3)

def Start(builder):
    StftParamStart(builder)

def StftParamAddNFft(builder, nFft):
    builder.PrependInt32Slot(0, nFft, 0)

def AddNFft(builder, nFft):
    StftParamAddNFft(builder, nFft)

def StftParamAddHopLength(builder, hopLength):
    builder.PrependInt32Slot(1, hopLength, 0)

def AddHopLength(builder, hopLength):
    StftParamAddHopLength(builder, hopLength)

def StftParamAddAbs(builder, abs):
    builder.PrependBoolSlot(2, abs, 1)

def AddAbs(builder, abs):
    StftParamAddAbs(builder, abs)

def StftParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return StftParamEnd(builder)
