# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TensorArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TensorArray()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTensorArray(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TensorArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TensorArray
    def DynamicSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TensorArray
    def IdenticalElementShapes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TensorArray
    def ElementShape(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TensorArray
    def ElementShapeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # TensorArray
    def ElementShapeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TensorArray
    def ElementShapeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # TensorArray
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # TensorArray
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TensorArray
    def Keepdims(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # TensorArray
    def NewAxis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def TensorArrayStart(builder):
    builder.StartObject(7)

def Start(builder):
    TensorArrayStart(builder)

def TensorArrayAddDynamicSize(builder, dynamicSize):
    builder.PrependBoolSlot(0, dynamicSize, 0)

def AddDynamicSize(builder, dynamicSize):
    TensorArrayAddDynamicSize(builder, dynamicSize)

def TensorArrayAddIdenticalElementShapes(builder, identicalElementShapes):
    builder.PrependBoolSlot(1, identicalElementShapes, 0)

def AddIdenticalElementShapes(builder, identicalElementShapes):
    TensorArrayAddIdenticalElementShapes(builder, identicalElementShapes)

def TensorArrayAddElementShape(builder, elementShape):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(elementShape), 0)

def AddElementShape(builder, elementShape):
    TensorArrayAddElementShape(builder, elementShape)

def TensorArrayStartElementShapeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartElementShapeVector(builder, numElems: int) -> int:
    return TensorArrayStartElementShapeVector(builder, numElems)

def TensorArrayAddT(builder, t):
    builder.PrependInt32Slot(3, t, 1)

def AddT(builder, t):
    TensorArrayAddT(builder, t)

def TensorArrayAddAxis(builder, axis):
    builder.PrependInt32Slot(4, axis, 0)

def AddAxis(builder, axis):
    TensorArrayAddAxis(builder, axis)

def TensorArrayAddKeepdims(builder, keepdims):
    builder.PrependBoolSlot(5, keepdims, 1)

def AddKeepdims(builder, keepdims):
    TensorArrayAddKeepdims(builder, keepdims)

def TensorArrayAddNewAxis(builder, newAxis):
    builder.PrependBoolSlot(6, newAxis, 0)

def AddNewAxis(builder, newAxis):
    TensorArrayAddNewAxis(builder, newAxis)

def TensorArrayEnd(builder):
    return builder.EndObject()

def End(builder):
    return TensorArrayEnd(builder)
