# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UnaryOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnaryOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnaryOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UnaryOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnaryOp
    def OpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UnaryOp
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UnaryOp
    def TableInt8(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # UnaryOp
    def TableInt8AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # UnaryOp
    def TableInt8Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UnaryOp
    def TableInt8IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def UnaryOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    UnaryOpStart(builder)

def UnaryOpAddOpType(builder, opType):
    builder.PrependInt32Slot(0, opType, 0)

def AddOpType(builder, opType):
    UnaryOpAddOpType(builder, opType)

def UnaryOpAddT(builder, t):
    builder.PrependInt32Slot(1, t, 0)

def AddT(builder, t):
    UnaryOpAddT(builder, t)

def UnaryOpAddTableInt8(builder, tableInt8):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tableInt8), 0)

def AddTableInt8(builder, tableInt8):
    UnaryOpAddTableInt8(builder, tableInt8)

def UnaryOpStartTableInt8Vector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartTableInt8Vector(builder, numElems: int) -> int:
    return UnaryOpStartTableInt8Vector(builder, numElems)

def UnaryOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return UnaryOpEnd(builder)
