# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArgMax(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArgMax()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArgMax(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ArgMax
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArgMax
    def OutMaxVal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArgMax
    def TopK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArgMax
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArgMax
    def SoftmaxThreshold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ArgMaxStart(builder):
    builder.StartObject(4)

def Start(builder):
    ArgMaxStart(builder)

def ArgMaxAddOutMaxVal(builder, outMaxVal):
    builder.PrependInt32Slot(0, outMaxVal, 0)

def AddOutMaxVal(builder, outMaxVal):
    ArgMaxAddOutMaxVal(builder, outMaxVal)

def ArgMaxAddTopK(builder, topK):
    builder.PrependInt32Slot(1, topK, 0)

def AddTopK(builder, topK):
    ArgMaxAddTopK(builder, topK)

def ArgMaxAddAxis(builder, axis):
    builder.PrependInt32Slot(2, axis, 0)

def AddAxis(builder, axis):
    ArgMaxAddAxis(builder, axis)

def ArgMaxAddSoftmaxThreshold(builder, softmaxThreshold):
    builder.PrependInt32Slot(3, softmaxThreshold, 0)

def AddSoftmaxThreshold(builder, softmaxThreshold):
    ArgMaxAddSoftmaxThreshold(builder, softmaxThreshold)

def ArgMaxEnd(builder):
    return builder.EndObject()

def End(builder):
    return ArgMaxEnd(builder)
