# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AttentionParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AttentionParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAttentionParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AttentionParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AttentionParam
    def KvCache(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def AttentionParamStart(builder):
    builder.StartObject(1)

def Start(builder):
    AttentionParamStart(builder)

def AttentionParamAddKvCache(builder, kvCache):
    builder.PrependBoolSlot(0, kvCache, 1)

def AddKvCache(builder, kvCache):
    AttentionParamAddKvCache(builder, kvCache)

def AttentionParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return AttentionParamEnd(builder)
