# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BatchMatMulParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchMatMulParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBatchMatMulParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BatchMatMulParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchMatMulParam
    def AdjX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # BatchMatMulParam
    def AdjY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BatchMatMulParamStart(builder):
    builder.StartObject(2)

def Start(builder):
    BatchMatMulParamStart(builder)

def BatchMatMulParamAddAdjX(builder, adjX):
    builder.PrependBoolSlot(0, adjX, 0)

def AddAdjX(builder, adjX):
    BatchMatMulParamAddAdjX(builder, adjX)

def BatchMatMulParamAddAdjY(builder, adjY):
    builder.PrependBoolSlot(1, adjY, 0)

def AddAdjY(builder, adjY):
    BatchMatMulParamAddAdjY(builder, adjY)

def BatchMatMulParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return BatchMatMulParamEnd(builder)
