# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

class CoordinateTransformationMode(object):
    NotSet = 0
    AlignCorners = 1
    HalfPixels = 2
    PytorchHalfPixels = 3
    Asymmetric = 4
    TensorflowHalfPixels = 5
    TensorflowCropAndResize = 6
