# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CumSum(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CumSum()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCumSum(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CumSum
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CumSum
    def Exclusive(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CumSum
    def Reverse(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def CumSumStart(builder):
    builder.StartObject(2)

def Start(builder):
    CumSumStart(builder)

def CumSumAddExclusive(builder, exclusive):
    builder.PrependBoolSlot(0, exclusive, 0)

def AddExclusive(builder, exclusive):
    CumSumAddExclusive(builder, exclusive)

def CumSumAddReverse(builder, reverse):
    builder.PrependBoolSlot(1, reverse, 0)

def AddReverse(builder, reverse):
    CumSumAddReverse(builder, reverse)

def CumSumEnd(builder):
    return builder.EndObject()

def End(builder):
    return CumSumEnd(builder)
