# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ELU(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ELU()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsELU(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ELU
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ELU
    def Alpha(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ELUStart(builder):
    builder.StartObject(1)

def Start(builder):
    ELUStart(builder)

def ELUAddAlpha(builder, alpha):
    builder.PrependFloat32Slot(0, alpha, 0.0)

def AddAlpha(builder, alpha):
    ELUAddAlpha(builder, alpha)

def ELUEnd(builder):
    return builder.EndObject()

def End(builder):
    return ELUEnd(builder)
