# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FmhcaParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FmhcaParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFmhcaParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FmhcaParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FmhcaParam
    def Heads(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def FmhcaParamStart(builder):
    builder.StartObject(1)

def Start(builder):
    FmhcaParamStart(builder)

def FmhcaParamAddHeads(builder, heads):
    builder.PrependInt32Slot(0, heads, 0)

def AddHeads(builder, heads):
    FmhcaParamAddHeads(builder, heads)

def FmhcaParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return FmhcaParamEnd(builder)
