# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

class ForwardType(object):
    CPU = 0
    METAL = 1
    CUDA = 2
    OPENCL = 3
    AUTO = 4
    NNAPI = 5
    OPENGLES = 6
    VULKAN = 7
