# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GridSample(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GridSample()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGridSample(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GridSample
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GridSample
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # GridSample
    def PaddingMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # GridSample
    def AlignCorners(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GridSample
    def Backward(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def GridSampleStart(builder):
    builder.StartObject(4)

def Start(builder):
    GridSampleStart(builder)

def GridSampleAddMode(builder, mode):
    builder.PrependInt8Slot(0, mode, 0)

def AddMode(builder, mode):
    GridSampleAddMode(builder, mode)

def GridSampleAddPaddingMode(builder, paddingMode):
    builder.PrependInt8Slot(1, paddingMode, 0)

def AddPaddingMode(builder, paddingMode):
    GridSampleAddPaddingMode(builder, paddingMode)

def GridSampleAddAlignCorners(builder, alignCorners):
    builder.PrependBoolSlot(2, alignCorners, 0)

def AddAlignCorners(builder, alignCorners):
    GridSampleAddAlignCorners(builder, alignCorners)

def GridSampleAddBackward(builder, backward):
    builder.PrependBoolSlot(3, backward, 0)

def AddBackward(builder, backward):
    GridSampleAddBackward(builder, backward)

def GridSampleEnd(builder):
    return builder.EndObject()

def End(builder):
    return GridSampleEnd(builder)
