# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImageProcessParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImageProcessParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImageProcessParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImageProcessParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImageProcessParam
    def FilterType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ImageProcessParam
    def SourceFormat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ImageProcessParam
    def DestFormat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ImageProcessParam
    def Wrap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ImageProcessParam
    def Mean(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ImageProcessParam
    def MeanAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ImageProcessParam
    def MeanLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImageProcessParam
    def MeanIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # ImageProcessParam
    def Normal(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ImageProcessParam
    def NormalAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ImageProcessParam
    def NormalLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImageProcessParam
    def NormalIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ImageProcessParam
    def Transform(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ImageProcessParam
    def TransformAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ImageProcessParam
    def TransformLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImageProcessParam
    def TransformIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # ImageProcessParam
    def PaddingValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ImageProcessParam
    def Shape(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ImageProcessParam
    def ShapeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # ImageProcessParam
    def ShapeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImageProcessParam
    def ShapeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # ImageProcessParam
    def OutputType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ImageProcessParam
    def Draw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ImageProcessParamStart(builder):
    builder.StartObject(11)

def Start(builder):
    ImageProcessParamStart(builder)

def ImageProcessParamAddFilterType(builder, filterType):
    builder.PrependInt8Slot(0, filterType, 0)

def AddFilterType(builder, filterType):
    ImageProcessParamAddFilterType(builder, filterType)

def ImageProcessParamAddSourceFormat(builder, sourceFormat):
    builder.PrependInt32Slot(1, sourceFormat, 0)

def AddSourceFormat(builder, sourceFormat):
    ImageProcessParamAddSourceFormat(builder, sourceFormat)

def ImageProcessParamAddDestFormat(builder, destFormat):
    builder.PrependInt32Slot(2, destFormat, 0)

def AddDestFormat(builder, destFormat):
    ImageProcessParamAddDestFormat(builder, destFormat)

def ImageProcessParamAddWrap(builder, wrap):
    builder.PrependInt8Slot(3, wrap, 0)

def AddWrap(builder, wrap):
    ImageProcessParamAddWrap(builder, wrap)

def ImageProcessParamAddMean(builder, mean):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(mean), 0)

def AddMean(builder, mean):
    ImageProcessParamAddMean(builder, mean)

def ImageProcessParamStartMeanVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMeanVector(builder, numElems: int) -> int:
    return ImageProcessParamStartMeanVector(builder, numElems)

def ImageProcessParamAddNormal(builder, normal):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(normal), 0)

def AddNormal(builder, normal):
    ImageProcessParamAddNormal(builder, normal)

def ImageProcessParamStartNormalVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNormalVector(builder, numElems: int) -> int:
    return ImageProcessParamStartNormalVector(builder, numElems)

def ImageProcessParamAddTransform(builder, transform):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(transform), 0)

def AddTransform(builder, transform):
    ImageProcessParamAddTransform(builder, transform)

def ImageProcessParamStartTransformVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTransformVector(builder, numElems: int) -> int:
    return ImageProcessParamStartTransformVector(builder, numElems)

def ImageProcessParamAddPaddingValue(builder, paddingValue):
    builder.PrependInt8Slot(7, paddingValue, 0)

def AddPaddingValue(builder, paddingValue):
    ImageProcessParamAddPaddingValue(builder, paddingValue)

def ImageProcessParamAddShape(builder, shape):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(shape), 0)

def AddShape(builder, shape):
    ImageProcessParamAddShape(builder, shape)

def ImageProcessParamStartShapeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShapeVector(builder, numElems: int) -> int:
    return ImageProcessParamStartShapeVector(builder, numElems)

def ImageProcessParamAddOutputType(builder, outputType):
    builder.PrependInt32Slot(9, outputType, 0)

def AddOutputType(builder, outputType):
    ImageProcessParamAddOutputType(builder, outputType)

def ImageProcessParamAddDraw(builder, draw):
    builder.PrependBoolSlot(10, draw, 0)

def AddDraw(builder, draw):
    ImageProcessParamAddDraw(builder, draw)

def ImageProcessParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return ImageProcessParamEnd(builder)
