# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LoopParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LoopParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLoopParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LoopParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LoopParam
    def TensorNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LoopParam
    def OutputIndexes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # LoopParam
    def OutputIndexesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # LoopParam
    def OutputIndexesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LoopParam
    def OutputIndexesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # LoopParam
    def InputIndexes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # LoopParam
    def InputIndexesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # LoopParam
    def InputIndexesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LoopParam
    def InputIndexesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # LoopParam
    def ExtraTensorInfos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MNN.TensorDescribe import TensorDescribe
            obj = TensorDescribe()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LoopParam
    def ExtraTensorInfosLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LoopParam
    def ExtraTensorInfosIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # LoopParam
    def Parallel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # LoopParam
    def LoopNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LoopParam
    def Commands(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MNN.RegionCommand import RegionCommand
            obj = RegionCommand()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LoopParam
    def CommandsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LoopParam
    def CommandsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # LoopParam
    def InitCommand(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MNN.RegionCommand import RegionCommand
            obj = RegionCommand()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LoopParam
    def InitCommandLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LoopParam
    def InitCommandIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def LoopParamStart(builder):
    builder.StartObject(8)

def Start(builder):
    LoopParamStart(builder)

def LoopParamAddTensorNumber(builder, tensorNumber):
    builder.PrependInt32Slot(0, tensorNumber, 0)

def AddTensorNumber(builder, tensorNumber):
    LoopParamAddTensorNumber(builder, tensorNumber)

def LoopParamAddOutputIndexes(builder, outputIndexes):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(outputIndexes), 0)

def AddOutputIndexes(builder, outputIndexes):
    LoopParamAddOutputIndexes(builder, outputIndexes)

def LoopParamStartOutputIndexesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputIndexesVector(builder, numElems: int) -> int:
    return LoopParamStartOutputIndexesVector(builder, numElems)

def LoopParamAddInputIndexes(builder, inputIndexes):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(inputIndexes), 0)

def AddInputIndexes(builder, inputIndexes):
    LoopParamAddInputIndexes(builder, inputIndexes)

def LoopParamStartInputIndexesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInputIndexesVector(builder, numElems: int) -> int:
    return LoopParamStartInputIndexesVector(builder, numElems)

def LoopParamAddExtraTensorInfos(builder, extraTensorInfos):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(extraTensorInfos), 0)

def AddExtraTensorInfos(builder, extraTensorInfos):
    LoopParamAddExtraTensorInfos(builder, extraTensorInfos)

def LoopParamStartExtraTensorInfosVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExtraTensorInfosVector(builder, numElems: int) -> int:
    return LoopParamStartExtraTensorInfosVector(builder, numElems)

def LoopParamAddParallel(builder, parallel):
    builder.PrependBoolSlot(4, parallel, 1)

def AddParallel(builder, parallel):
    LoopParamAddParallel(builder, parallel)

def LoopParamAddLoopNumber(builder, loopNumber):
    builder.PrependInt32Slot(5, loopNumber, 0)

def AddLoopNumber(builder, loopNumber):
    LoopParamAddLoopNumber(builder, loopNumber)

def LoopParamAddCommands(builder, commands):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(commands), 0)

def AddCommands(builder, commands):
    LoopParamAddCommands(builder, commands)

def LoopParamStartCommandsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCommandsVector(builder, numElems: int) -> int:
    return LoopParamStartCommandsVector(builder, numElems)

def LoopParamAddInitCommand(builder, initCommand):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(initCommand), 0)

def AddInitCommand(builder, initCommand):
    LoopParamAddInitCommand(builder, initCommand)

def LoopParamStartInitCommandVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInitCommandVector(builder, numElems: int) -> int:
    return LoopParamStartInitCommandVector(builder, numElems)

def LoopParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return LoopParamEnd(builder)
