# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Plugin(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Plugin()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlugin(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Plugin
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Plugin
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Plugin
    def Attr(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MNN.Attribute import Attribute
            obj = Attribute()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Plugin
    def AttrLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Plugin
    def AttrIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def PluginStart(builder):
    builder.StartObject(2)

def Start(builder):
    PluginStart(builder)

def PluginAddType(builder, type):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def AddType(builder, type):
    PluginAddType(builder, type)

def PluginAddAttr(builder, attr):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(attr), 0)

def AddAttr(builder, attr):
    PluginAddAttr(builder, attr)

def PluginStartAttrVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAttrVector(builder, numElems: int) -> int:
    return PluginStartAttrVector(builder, numElems)

def PluginEnd(builder):
    return builder.EndObject()

def End(builder):
    return PluginEnd(builder)
