# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuantizedRelu(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuantizedRelu()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuantizedRelu(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuantizedRelu
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizedRelu
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def QuantizedReluStart(builder):
    builder.StartObject(1)

def Start(builder):
    QuantizedReluStart(builder)

def QuantizedReluAddType(builder, type):
    builder.PrependInt32Slot(0, type, 0)

def AddType(builder, type):
    QuantizedReluAddType(builder, type)

def QuantizedReluEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuantizedReluEnd(builder)
