# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuantizedParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuantizedParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuantizedParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuantizedParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizedParam
    def ZeroPoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # QuantizedParam
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def QuantizedParamStart(builder):
    builder.StartObject(2)

def Start(builder):
    QuantizedParamStart(builder)

def QuantizedParamAddZeroPoint(builder, zeroPoint):
    builder.PrependInt32Slot(0, zeroPoint, 0)

def AddZeroPoint(builder, zeroPoint):
    QuantizedParamAddZeroPoint(builder, zeroPoint)

def QuantizedParamAddScale(builder, scale):
    builder.PrependFloat32Slot(1, scale, 0.0)

def AddScale(builder, scale):
    QuantizedParamAddScale(builder, scale)

def QuantizedParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuantizedParamEnd(builder)
