# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuantizedLogistic(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuantizedLogistic()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuantizedLogistic(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuantizedLogistic
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizedLogistic
    def InputQuantizedParam(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MNN.QuantizedParam import QuantizedParam
            obj = QuantizedParam()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QuantizedLogistic
    def OutputQuantizedParam(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MNN.QuantizedParam import QuantizedParam
            obj = QuantizedParam()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def QuantizedLogisticStart(builder):
    builder.StartObject(2)

def Start(builder):
    QuantizedLogisticStart(builder)

def QuantizedLogisticAddInputQuantizedParam(builder, inputQuantizedParam):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(inputQuantizedParam), 0)

def AddInputQuantizedParam(builder, inputQuantizedParam):
    QuantizedLogisticAddInputQuantizedParam(builder, inputQuantizedParam)

def QuantizedLogisticAddOutputQuantizedParam(builder, outputQuantizedParam):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(outputQuantizedParam), 0)

def AddOutputQuantizedParam(builder, outputQuantizedParam):
    QuantizedLogisticAddOutputQuantizedParam(builder, outputQuantizedParam)

def QuantizedLogisticEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuantizedLogisticEnd(builder)
