# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuantizedRelu6(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuantizedRelu6()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuantizedRelu6(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuantizedRelu6
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizedRelu6
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def QuantizedRelu6Start(builder):
    builder.StartObject(1)

def Start(builder):
    QuantizedRelu6Start(builder)

def QuantizedRelu6AddType(builder, type):
    builder.PrependInt32Slot(0, type, 0)

def AddType(builder, type):
    QuantizedRelu6AddType(builder, type)

def QuantizedRelu6End(builder):
    return builder.EndObject()

def End(builder):
    return QuantizedRelu6End(builder)
