# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuantizedSoftmax(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuantizedSoftmax()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuantizedSoftmax(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuantizedSoftmax
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizedSoftmax
    def Beta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # QuantizedSoftmax
    def InputScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def QuantizedSoftmaxStart(builder):
    builder.StartObject(2)

def Start(builder):
    QuantizedSoftmaxStart(builder)

def QuantizedSoftmaxAddBeta(builder, beta):
    builder.PrependFloat32Slot(0, beta, 0.0)

def AddBeta(builder, beta):
    QuantizedSoftmaxAddBeta(builder, beta)

def QuantizedSoftmaxAddInputScale(builder, inputScale):
    builder.PrependFloat32Slot(1, inputScale, 0.0)

def AddInputScale(builder, inputScale):
    QuantizedSoftmaxAddInputScale(builder, inputScale)

def QuantizedSoftmaxEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuantizedSoftmaxEnd(builder)
