# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Requantize(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Requantize()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequantize(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Requantize
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def RequantizeStart(builder):
    builder.StartObject(0)

def Start(builder):
    RequantizeStart(builder)

def RequantizeEnd(builder):
    return builder.EndObject()

def End(builder):
    return RequantizeEnd(builder)
