# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RoiParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RoiParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRoiParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RoiParameters
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RoiParameters
    def PooledWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RoiParameters
    def PooledHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RoiParameters
    def SpatialScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RoiParameters
    def SamplingRatio(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # RoiParameters
    def Aligned(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # RoiParameters
    def PoolType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 1

    # RoiParameters
    def OutputGrad(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def RoiParametersStart(builder):
    builder.StartObject(7)

def Start(builder):
    RoiParametersStart(builder)

def RoiParametersAddPooledWidth(builder, pooledWidth):
    builder.PrependInt32Slot(0, pooledWidth, 0)

def AddPooledWidth(builder, pooledWidth):
    RoiParametersAddPooledWidth(builder, pooledWidth)

def RoiParametersAddPooledHeight(builder, pooledHeight):
    builder.PrependInt32Slot(1, pooledHeight, 0)

def AddPooledHeight(builder, pooledHeight):
    RoiParametersAddPooledHeight(builder, pooledHeight)

def RoiParametersAddSpatialScale(builder, spatialScale):
    builder.PrependFloat32Slot(2, spatialScale, 0.0)

def AddSpatialScale(builder, spatialScale):
    RoiParametersAddSpatialScale(builder, spatialScale)

def RoiParametersAddSamplingRatio(builder, samplingRatio):
    builder.PrependInt32Slot(3, samplingRatio, -1)

def AddSamplingRatio(builder, samplingRatio):
    RoiParametersAddSamplingRatio(builder, samplingRatio)

def RoiParametersAddAligned(builder, aligned):
    builder.PrependBoolSlot(4, aligned, 0)

def AddAligned(builder, aligned):
    RoiParametersAddAligned(builder, aligned)

def RoiParametersAddPoolType(builder, poolType):
    builder.PrependInt8Slot(5, poolType, 1)

def AddPoolType(builder, poolType):
    RoiParametersAddPoolType(builder, poolType)

def RoiParametersAddOutputGrad(builder, outputGrad):
    builder.PrependBoolSlot(6, outputGrad, 0)

def AddOutputGrad(builder, outputGrad):
    RoiParametersAddOutputGrad(builder, outputGrad)

def RoiParametersEnd(builder):
    return builder.EndObject()

def End(builder):
    return RoiParametersEnd(builder)
