# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Selu(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Selu()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSelu(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Selu
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Selu
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Selu
    def Alpha(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SeluStart(builder):
    builder.StartObject(2)

def Start(builder):
    SeluStart(builder)

def SeluAddScale(builder, scale):
    builder.PrependFloat32Slot(0, scale, 0.0)

def AddScale(builder, scale):
    SeluAddScale(builder, scale)

def SeluAddAlpha(builder, alpha):
    builder.PrependFloat32Slot(1, alpha, 0.0)

def AddAlpha(builder, alpha):
    SeluAddAlpha(builder, alpha)

def SeluEnd(builder):
    return builder.EndObject()

def End(builder):
    return SeluEnd(builder)
