# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SliceTf(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SliceTf()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSliceTf(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SliceTf
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SliceTf
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def SliceTfStart(builder):
    builder.StartObject(1)

def Start(builder):
    SliceTfStart(builder)

def SliceTfAddT(builder, t):
    builder.PrependInt32Slot(0, t, 0)

def AddT(builder, t):
    SliceTfAddT(builder, t)

def SliceTfEnd(builder):
    return builder.EndObject()

def End(builder):
    return SliceTfEnd(builder)
