# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Slice(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Slice()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSlice(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Slice
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Slice
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Slice
    def SlicePoints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Slice
    def SlicePointsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Slice
    def SlicePointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Slice
    def SlicePointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Slice
    def SourceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def SliceStart(builder):
    builder.StartObject(3)

def Start(builder):
    SliceStart(builder)

def SliceAddAxis(builder, axis):
    builder.PrependInt32Slot(0, axis, 0)

def AddAxis(builder, axis):
    SliceAddAxis(builder, axis)

def SliceAddSlicePoints(builder, slicePoints):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(slicePoints), 0)

def AddSlicePoints(builder, slicePoints):
    SliceAddSlicePoints(builder, slicePoints)

def SliceStartSlicePointsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSlicePointsVector(builder, numElems: int) -> int:
    return SliceStartSlicePointsVector(builder, numElems)

def SliceAddSourceType(builder, sourceType):
    builder.PrependInt8Slot(2, sourceType, 0)

def AddSourceType(builder, sourceType):
    SliceAddSourceType(builder, sourceType)

def SliceEnd(builder):
    return builder.EndObject()

def End(builder):
    return SliceEnd(builder)
