# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SqueezeParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SqueezeParam()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSqueezeParam(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SqueezeParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SqueezeParam
    def SqueezeDims(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SqueezeParam
    def SqueezeDimsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # SqueezeParam
    def SqueezeDimsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SqueezeParam
    def SqueezeDimsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SqueezeParamStart(builder):
    builder.StartObject(1)

def Start(builder):
    SqueezeParamStart(builder)

def SqueezeParamAddSqueezeDims(builder, squeezeDims):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(squeezeDims), 0)

def AddSqueezeDims(builder, squeezeDims):
    SqueezeParamAddSqueezeDims(builder, squeezeDims)

def SqueezeParamStartSqueezeDimsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSqueezeDimsVector(builder, numElems: int) -> int:
    return SqueezeParamStartSqueezeDimsVector(builder, numElems)

def SqueezeParamEnd(builder):
    return builder.EndObject()

def End(builder):
    return SqueezeParamEnd(builder)
