# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TopKV2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TopKV2()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTopKV2(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TopKV2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TopKV2
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # TopKV2
    def Sorted(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TopKV2
    def Largest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def TopKV2Start(builder):
    builder.StartObject(3)

def Start(builder):
    TopKV2Start(builder)

def TopKV2AddT(builder, t):
    builder.PrependInt32Slot(0, t, 1)

def AddT(builder, t):
    TopKV2AddT(builder, t)

def TopKV2AddSorted(builder, sorted):
    builder.PrependBoolSlot(1, sorted, 0)

def AddSorted(builder, sorted):
    TopKV2AddSorted(builder, sorted)

def TopKV2AddLargest(builder, largest):
    builder.PrependBoolSlot(2, largest, 1)

def AddLargest(builder, largest):
    TopKV2AddLargest(builder, largest)

def TopKV2End(builder):
    return builder.EndObject()

def End(builder):
    return TopKV2End(builder)
