# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Transpose(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Transpose()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTranspose(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Transpose
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Transpose
    def Tperm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def TransposeStart(builder):
    builder.StartObject(1)

def Start(builder):
    TransposeStart(builder)

def TransposeAddTperm(builder, tperm):
    builder.PrependInt32Slot(0, tperm, 0)

def AddTperm(builder, tperm):
    TransposeAddTperm(builder, tperm)

def TransposeEnd(builder):
    return builder.EndObject()

def End(builder):
    return TransposeEnd(builder)
